var registro_especies = {
"type": "FeatureCollection",
"name": "registro_especies",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ID_REGISTR": 587.0, "CITACION_B": "OLIVARES, A. 1971. Las ciconiiformes de Col. garzas,coclea- rius, cigüeñas ibis, espátula. Ed. Tercer Mundo-Colombia.", "FECHA_EVEN": null, "HABITAT": null, "PAIS": "Colombia", "DEPARTAMEN": "Valle del Cauca", "MUNICIPIO": "LA UNION", "CORREGIMIE": "ZONA URBANA", "LOCALIDAD": "Lemos (nombre que recibía el Mpio. de La Union entre 1936-1941).Parte superior del Valle en la base oriental de la C. Occidental 35 km SW de Cartago y 14 km WNW de Victoria", "ELEVACION_": 964.0, "CUENCA": "RUT", "AREA_PROTE": null, "COD_AREA_E": null, "PREDIO": null, "PROPIETARI": null, "COORD_X": 1108800.0, "COORD_Y": 993100.0, "REINO": "Animalia", "PILO_DIVIS": "Chordata", "CLASE": "Aves", "ORDEN": "Ciconiiformes", "FAMILIA": "Threskiornithidae", "GENERO": "Platalea", "EPITETO_ES": "ajaja", "NOMBRE_CIE": "Platalea ajaja", "AUTORIA_NO": "Linnaeus, 1758", "NOMBRE_COM": "PATO CUCHARA", "CODIGO_CVC": "ABNGE05010" }, "geometry": { "type": "Point", "coordinates": [ -76.097141944884427, 4.533137560119321 ] } },
{ "type": "Feature", "properties": { "ID_REGISTR": 2465.0, "CITACION_B": "FANDIÑO, J. 1982. Inventario especies forestales vedadas. Sector norte. Informe presentado a CVC. Cali. Contiene mapa y actas de notificación.", "FECHA_EVEN": null, "HABITAT": null, "PAIS": "Colombia", "DEPARTAMEN": "Valle del Cauca", "MUNICIPIO": "LA UNION", "CORREGIMIE": "CORCEGA", "LOCALIDAD": "Margen izquierda del Río Cauca", "ELEVACION_": 0.0, "CUENCA": "RUT", "AREA_PROTE": null, "COD_AREA_E": null, "PREDIO": "HACIENDA LAS VEGAS", "PROPIETARI": "A. M. Posso (M. Rodríguez,...)", "COORD_X": 1110650.0, "COORD_Y": 993770.0, "REINO": "Plantae", "PILO_DIVIS": "Magnoliophyta", "CLASE": "Magnoliopsida", "ORDEN": "Sapindales", "FAMILIA": "Anacardiaceae", "GENERO": "Anacardium", "EPITETO_ES": "excelsum", "NOMBRE_CIE": "Anacardium excelsum", "AUTORIA_NO": "(Kunth) Skeels", "NOMBRE_COM": "CARACOLI", "CODIGO_CVC": "PDANA01020" }, "geometry": { "type": "Point", "coordinates": [ -76.080465500418157, 4.539172715928127 ] } },
{ "type": "Feature", "properties": { "ID_REGISTR": 2185.0, "CITACION_B": "FANDIÑO, J. 1982. Inventario especies forestales vedadas. Sector norte. Informe presentado a CVC. Cali. Contiene mapa y actas de notificación.", "FECHA_EVEN": null, "HABITAT": null, "PAIS": "Colombia", "DEPARTAMEN": "Valle del Cauca", "MUNICIPIO": "LA UNION", "CORREGIMIE": "CORCEGA", "LOCALIDAD": "Entre Córcega y La Unión", "ELEVACION_": 0.0, "CUENCA": "RUT", "AREA_PROTE": null, "COD_AREA_E": null, "PREDIO": "HACIENDA LAS PLAYAS", "PROPIETARI": "SALUSTIANO GARCÍA", "COORD_X": 1111400.0, "COORD_Y": 993500.0, "REINO": "Plantae", "PILO_DIVIS": "Magnoliophyta", "CLASE": "Magnoliopsida", "ORDEN": "Magnoliales", "FAMILIA": "Annonaceae", "GENERO": "Xylopia", "EPITETO_ES": "ligustrifolia", "NOMBRE_CIE": "Xylopia ligustrifolia", "AUTORIA_NO": "Humb. & Bonpl. ex Dunal", "NOMBRE_COM": "BURILICO", "CODIGO_CVC": "PD01005370" }, "geometry": { "type": "Point", "coordinates": [ -76.073711488416322, 4.536722077340468 ] } },
{ "type": "Feature", "properties": { "ID_REGISTR": 2201.0, "CITACION_B": "FANDIÑO, J. 1982. Inventario especies forestales vedadas. Sector norte. Informe presentado a CVC. Cali. Contiene mapa y actas de notificación.", "FECHA_EVEN": null, "HABITAT": null, "PAIS": "Colombia", "DEPARTAMEN": "Valle del Cauca", "MUNICIPIO": "LA UNION", "CORREGIMIE": "CORCEGA", "LOCALIDAD": "Margen izquierda del Río Cauca", "ELEVACION_": 0.0, "CUENCA": "RUT", "AREA_PROTE": null, "COD_AREA_E": null, "PREDIO": "HACIENDA LAS VEGAS", "PROPIETARI": "Angel M. Posso", "COORD_X": 1112450.0, "COORD_Y": 993850.0, "REINO": "Plantae", "PILO_DIVIS": "Magnoliophyta", "CLASE": "Magnoliopsida", "ORDEN": "Malvales", "FAMILIA": "Bombacaceae", "GENERO": "Quararibea", "EPITETO_ES": "ciroana", "NOMBRE_CIE": "Quararibea ciroana", "AUTORIA_NO": "Cuatrec.", "NOMBRE_COM": null, "CODIGO_CVC": "PDBOM04040" }, "geometry": { "type": "Point", "coordinates": [ -76.06424679280336, 4.539873453775305 ] } }
]
}
